#!/bin/bash

ROL_PATH=`python -c "import os; import RoboticsLanguage; print os.path.dirname(os.path.abspath(RoboticsLanguage.__file__)) + '/..'"`

echo "Initialising Docker..."

docker run -it --rm -v $ROL_PATH:/RoL --workdir=/RoL --name=RoboticsLanguage osrf/ros:kinetic-desktop bash -c "source ./RoboticsLanguage/Scripts/docker/rol_source_in_docker_developer.sh; bash"
