#!/bin/bash

if [ ! "$(docker ps -q -f name=RoboticsLanguage2)" ]; then
  docker run -it --rm --name=RoboticsLanguage2 roboticslanguage/rol:ros2 bash
else
  docker exec -i -t RoboticsLanguage2 /bin/bash
fi
