#!/bin/bash

ROL_PATH=`python -c "import os; import RoboticsLanguage; print os.path.dirname(os.path.abspath(RoboticsLanguage.__file__))"`

# @NOTE Why did this stop working?
# python -m unittest discover -s $ROL_PATH/Scripts/tests/ -v

cd $ROL_PATH/Scripts/tests
python -m unittest -v test_rol_parse
python -m unittest -v test_base_transformations
python -m unittest -v test_base_utilities
python -m unittest -v test_base_commandline
