#!/bin/bash

if [ ! "$(docker ps -q -f name=AWSRoboticsLanguage)" ]; then
  docker run -it --rm --name=AWSRoboticsLanguage -p 9090:9090 -p 8000:80 roboticslanguage/rol bash
else
  docker exec -i -t AWSRoboticsLanguage /bin/bash
fi
