#!/bin/bash

if [ ! "$(docker ps -q -f name=RoboticsLanguage)" ]; then
  docker run -it --rm --name=RoboticsLanguage -p 9090:9090 -p 8000:80 roboticslanguage/rol bash
else
  docker exec -i -t RoboticsLanguage /bin/bash
fi
